### ISSUE TITLE
Ncursesw does not recognize new  library connection after rebuild.

### ISSUE THREAD

**Issue by masterkorp** [sup-heliotrope/ncursesw-ruby#31]
A ``gem pristine ncursesw`` did not rebuild the library links. A uninstall and install was necessary.

Related to https://github.com/sup-heliotrope/sup/issues/485

**Comment by gauteh** [comment]
It is weird that extconf.rb is not re-run, I thought that was the whole point of gem pristine. I think we need some debug output and log files from the gem rebuild.

**Comment by gauteh** [comment]
From http://guides.rubygems.org/command-reference/#gem-pristine

```Restores installed gems to pristine condition from files located in the gem cache```

this probably means that it is not re-built unless there is some difference to the cache. I belive the --all keyword should do it anyway.

**Comment by gauteh** [comment]
The correct fix is to rebuild: https://github.com/sup-heliotrope/sup/wiki/ncurses-dependency-update-from-5-to-6
